name: build kit.optimade.science

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: basf/svelte-spectre

      - name: Install
        run: |
          npm install

      - name: Format
        run: |
          npm run format

      - name: Build
        run: |
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
